import { useEffect, useState } from 'react'
import { Plus, Pencil, Trash2, X, CheckSquare, Users, Clock, GripVertical, CalendarDays } from 'lucide-react'
import { useAuth } from '../context/AuthContext'
import { getUsuarios } from '../lib/supabase'
import { getBancoTarefas, createBancoTarefa, updateBancoTarefa, desativarBancoTarefa, setResponsaveisBanco, setChecklistPadrao } from '../lib/banco-tarefas'

const PERFIS_INFLUENCERS = ['supervisor_influencers', 'analista_influencers', 'estagiario_influencers']
const PERIODICIDADES = [['avulsa','Avulsa'],['diaria','Diária'],['semanal','Semanal'],['quinzenal','Quinzenal'],['mensal','Mensal'],['anual','Anual']]
const PREFIXO = /^\[\[D-(\d+)\]\]\s*/
const FORM_VAZIO = { nome:'', descricao:'', periodicidade:'avulsa', responsaveis_ids:[], tempo_medio_minutos:'', checklist:[] }

function decodificar(texto) {
  const match = String(texto || '').match(PREFIXO)
  return { texto:String(texto || '').replace(PREFIXO, ''), dias_antes:match ? Number(match[1]) : 0 }
}
function codificar(item) {
  const dias = Math.max(0, Number(item.dias_antes) || 0)
  return `${dias > 0 ? `[[D-${dias}]] ` : ''}${String(item.texto || '').trim()}`
}

export default function ModelosTarefasInfluencers() {
  const { usuario } = useAuth()
  const [modelos,setModelos] = useState([]), [usuarios,setUsuarios] = useState([]), [loading,setLoading] = useState(true)
  const [modal,setModal] = useState(false), [editando,setEditando] = useState(null), [form,setForm] = useState(FORM_VAZIO)
  const [novoItem,setNovoItem] = useState(''), [novosDias,setNovosDias] = useState(0), [salvando,setSalvando] = useState(false)
  const [dragIndex,setDragIndex] = useState(null), [dragOver,setDragOver] = useState(null)

  async function carregar(){ setLoading(true); try { const [m,u]=await Promise.all([getBancoTarefas('influencers'),getUsuarios()]); setModelos(m||[]); setUsuarios((u||[]).filter(x=>PERFIS_INFLUENCERS.includes(x.perfil))) } finally { setLoading(false) } }
  useEffect(()=>{carregar()},[])

  function abrirNovo(){ setEditando(null); setForm(FORM_VAZIO); setNovoItem(''); setNovosDias(0); setModal(true) }
  function abrirEditar(modelo){ setEditando(modelo); setForm({ nome:modelo.nome||'', descricao:modelo.descricao||'', periodicidade:modelo.periodicidade||'avulsa', responsaveis_ids:(modelo.responsaveis_padrao||[]).map(r=>r.usuario_id), tempo_medio_minutos:modelo.tempo_medio_minutos||'', checklist:(modelo.checklist_padrao||[]).sort((a,b)=>(a.ordem||0)-(b.ordem||0)).map(c=>decodificar(c.texto)) }); setNovoItem(''); setNovosDias(0); setModal(true) }
  function toggleResponsavel(id){ setForm(f=>({...f,responsaveis_ids:f.responsaveis_ids.includes(id)?f.responsaveis_ids.filter(x=>x!==id):[...f.responsaveis_ids,id]})) }
  function adicionarChecklist(){ const texto=novoItem.trim(); if(!texto)return; setForm(f=>({...f,checklist:[...f.checklist,{texto,dias_antes:Math.max(0,Number(novosDias)||0)}]})); setNovoItem(''); setNovosDias(0) }
  function soltar(alvo){ if(dragIndex===null||dragIndex===alvo){setDragIndex(null);setDragOver(null);return} setForm(f=>{const itens=[...f.checklist]; const [movido]=itens.splice(dragIndex,1); itens.splice(alvo,0,movido); return {...f,checklist:itens}}); setDragIndex(null); setDragOver(null) }

  async function salvar(){ if(!form.nome.trim())return alert('Informe o nome do modelo.'); setSalvando(true); try { const payload={nome:form.nome.trim(),descricao:form.descricao.trim()||null,periodicidade:form.periodicidade,responsavel_id:form.responsaveis_ids[0]||null,tempo_medio_minutos:form.tempo_medio_minutos?Number(form.tempo_medio_minutos):null,created_by:usuario.id}; const salvo=editando?await updateBancoTarefa(editando.id,payload):await createBancoTarefa({...payload,grupo:'influencers'}); await setResponsaveisBanco(salvo.id,form.responsaveis_ids); await setChecklistPadrao(salvo.id,form.checklist.map(codificar)); setModal(false); await carregar() } catch(e){alert('Erro ao salvar modelo: '+(e.message||'erro desconhecido'))} finally{setSalvando(false)} }
  async function remover(id){ if(!window.confirm('Desativar este modelo? As tarefas já criadas continuarão existindo.'))return; await desativarBancoTarefa(id); setModelos(prev=>prev.filter(m=>m.id!==id)) }

  const idsVisiveis=new Set(usuarios.map(u=>u.id)); const responsaveisInativos=(editando?.responsaveis_padrao||[]).filter(r=>form.responsaveis_ids.includes(r.usuario_id)&&!idsVisiveis.has(r.usuario_id))

  return <div>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginBottom:18,flexWrap:'wrap'}}><div><h2 style={{margin:0,fontSize:18,color:'var(--text)'}}>Biblioteca de modelos</h2><p style={{margin:'4px 0 0',fontSize:12,color:'var(--text-muted)'}}>Defina tarefas reutilizáveis e quando cada etapa deve vencer.</p></div><button className="btn btn-primary" onClick={abrirNovo}><Plus size={14}/> Novo modelo</button></div>
    {loading?<div className="loading"><div className="spinner"/></div>:modelos.length===0?<div className="empty-state"><p>Nenhum modelo cadastrado.</p></div>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:12}}>{modelos.map(modelo=>{const checklist=modelo.checklist_padrao||[]; const responsaveis=(modelo.responsaveis_padrao||[]).map(r=>r.usuario?.nome).filter(Boolean); return <div key={modelo.id} style={{background:'var(--surface)',border:'1px solid var(--border)',borderRadius:12,padding:16}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><div style={{fontSize:14,fontWeight:700}}>{modelo.nome}</div>{modelo.descricao&&<p style={{fontSize:12,color:'var(--text-muted)',lineHeight:1.45}}>{modelo.descricao}</p>}</div><div style={{display:'flex',gap:4}}><button className="btn btn-ghost btn-icon btn-sm" onClick={()=>abrirEditar(modelo)}><Pencil size={12}/></button><button className="btn btn-danger btn-icon btn-sm" onClick={()=>remover(modelo.id)}><Trash2 size={12}/></button></div></div><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:12,fontSize:11,color:'var(--text-muted)'}}><span><Clock size={11}/> {PERIODICIDADES.find(x=>x[0]===modelo.periodicidade)?.[1]||'Avulsa'}</span><span><CheckSquare size={11}/> {checklist.length} etapa(s)</span><span><Users size={11}/> {responsaveis.length?responsaveis.join(', '):'Sem responsável padrão'}</span></div></div>})}</div>}

    {modal&&<div className="modal-backdrop"><div className="modal" style={{maxWidth:720,maxHeight:'92vh',overflowY:'auto'}}><div className="modal-header" style={{position:'sticky',top:0,background:'var(--surface)',zIndex:5}}><h2 className="modal-title">{editando?'Editar modelo':'Novo modelo'}</h2><button className="btn btn-ghost btn-icon" onClick={()=>setModal(false)}><X size={16}/></button></div><div className="form-grid">
      <div className="form-group"><label className="form-label">Nome do modelo *</label><input className="form-input" value={form.nome} onChange={e=>setForm(f=>({...f,nome:e.target.value}))}/></div>
      <div className="form-group"><label className="form-label">Descrição e instruções</label><textarea className="form-textarea" rows={3} value={form.descricao} onChange={e=>setForm(f=>({...f,descricao:e.target.value}))}/></div>
      <div className="form-row"><div className="form-group"><label className="form-label">Periodicidade</label><select className="form-select" value={form.periodicidade} onChange={e=>setForm(f=>({...f,periodicidade:e.target.value}))}>{PERIODICIDADES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="form-group"><label className="form-label">Tempo médio em minutos</label><input className="form-input" type="number" min="1" value={form.tempo_medio_minutos} onChange={e=>setForm(f=>({...f,tempo_medio_minutos:e.target.value}))}/></div></div>
      <div className="form-group"><label className="form-label">Responsável padrão</label><div style={{display:'flex',flexWrap:'wrap',gap:7}}>{responsaveisInativos.map(r=><button key={r.usuario_id} type="button" onClick={()=>toggleResponsavel(r.usuario_id)} style={{padding:'5px 12px',borderRadius:20,border:'1px solid #ef4444',background:'rgba(239,68,68,.12)',color:'#ef4444',cursor:'pointer'}}>{r.usuario?.nome?.split(' ')[0]||'Usuário inativo'} · remover</button>)}{usuarios.map(u=>{const ativo=form.responsaveis_ids.includes(u.id); return <button key={u.id} type="button" onClick={()=>toggleResponsavel(u.id)} style={{padding:'5px 12px',borderRadius:20,border:`1px solid ${ativo?'var(--accent)':'var(--border)'}`,background:ativo?'var(--accent-glow)':'transparent',color:ativo?'var(--accent)':'var(--text-muted)',cursor:'pointer'}}>{u.nome.split(' ')[0]}</button>})}</div></div>
      <div className="form-group"><label className="form-label">Checklist padrão</label><div style={{fontSize:11,color:'var(--text-muted)',marginBottom:8}}>Arraste para ordenar. Informe quantos dias antes do prazo final cada etapa deve vencer.</div>{form.checklist.map((item,i)=><div key={i} draggable onDragStart={()=>setDragIndex(i)} onDragOver={e=>{e.preventDefault();setDragOver(i)}} onDrop={()=>soltar(i)} onDragEnd={()=>{setDragIndex(null);setDragOver(null)}} style={{display:'grid',gridTemplateColumns:'28px 1fr 150px 34px',gap:7,alignItems:'center',marginBottom:7,padding:6,border:`1px solid ${dragOver===i?'var(--accent)':'var(--border)'}`,borderRadius:8,background:'var(--surface-2)',opacity:dragIndex===i?.55:1}}><span title="Arrastar" style={{cursor:'grab',display:'flex',justifyContent:'center',color:'var(--text-muted)'}}><GripVertical size={16}/></span><input className="form-input" value={item.texto} onChange={e=>setForm(f=>({...f,checklist:f.checklist.map((x,idx)=>idx===i?{...x,texto:e.target.value}:x)}))}/><div style={{position:'relative'}}><CalendarDays size={13} style={{position:'absolute',left:9,top:12,color:'var(--text-muted)'}}/><input className="form-input" type="number" min="0" value={item.dias_antes} onChange={e=>setForm(f=>({...f,checklist:f.checklist.map((x,idx)=>idx===i?{...x,dias_antes:Math.max(0,Number(e.target.value)||0)}:x)}))} style={{paddingLeft:28}} title="Dias antes do prazo final"/><span style={{position:'absolute',right:8,top:11,fontSize:10,color:'var(--text-muted)'}}>dias antes</span></div><button className="btn btn-ghost btn-icon btn-sm" onClick={()=>setForm(f=>({...f,checklist:f.checklist.filter((_,idx)=>idx!==i)}))}><Trash2 size={12}/></button></div>)}<div style={{display:'grid',gridTemplateColumns:'1fr 150px auto',gap:7}}><input className="form-input" value={novoItem} onChange={e=>setNovoItem(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();adicionarChecklist()}}} placeholder="Adicionar etapa..."/><input className="form-input" type="number" min="0" value={novosDias} onChange={e=>setNovosDias(Math.max(0,Number(e.target.value)||0))} placeholder="Dias antes"/><button className="btn btn-ghost" type="button" onClick={adicionarChecklist}><Plus size={13}/> Adicionar</button></div></div>
    </div><div className="form-actions"><button className="btn btn-ghost" onClick={()=>setModal(false)}>Cancelar</button><button className="btn btn-primary" onClick={salvar} disabled={salvando}>{salvando?'Salvando...':'Salvar modelo'}</button></div></div></div>}
  </div>
}
